# Generated by Django 4.2.6 on 2023-10-20 06:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0002_record_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='content',
            field=ckeditor.fields.RichTextField(default=True),
            preserve_default=False,
        ),
    ]
