# Generated by Django 4.1.4 on 2023-10-20 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0007_alter_avatar_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
