# Generated by Django 4.1.4 on 2023-10-21 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0009_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imagen',
            new_name='image',
        ),
    ]
