# Generated by Django 4.2.6 on 2023-10-23 22:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=150, null=True),
        ),
    ]
