# Generated by Django 4.2.6 on 2023-10-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0014_alter_profile_image_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/uploads'),
        ),
    ]
