# Generated by Django 4.2.6 on 2023-10-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0020_alter_profile_description_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images.png', null=True, upload_to='avatar/uploads/'),
        ),
    ]
