# Generated by Django 4.2.6 on 2023-11-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0021_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
